
#define TPU_BASE (0xfffffe00L)

#define TPU_TMCR	(*(short int *) (TPU_BASE))
#define TPU_TTCR	(*(short int *) (TPU_BASE+0x02))
#define TPU_DSCR     	(*(short int *) (TPU_BASE+0X04))
#define TPU_DSSR        (*(short int *) (TPU_BASE+0x06))
#define TPU_TICR 	(*(short int *) (TPU_BASE+0x08))
#define TPU_CIER	(*(short int *) (TPU_BASE+0x0a))
#define TPU_CFSR0	(*(short int *) (TPU_BASE+0x0c))
#define TPU_CFSR1 	(*(short int *) (TPU_BASE+0x0e))
#define TPU_CFSR2     	(*(short int *) (TPU_BASE+0x10))
#define TPU_CFSR3	(*(short int *) (TPU_BASE+0x12))
#define TPU_HSQR0	(*(short int *) (TPU_BASE+0x14))
#define TPU_HSQR1	(*(short int *) (TPU_BASE+0x16))
#define TPU_HSRR0     	(*(short int *) (TPU_BASE+0x18))
#define TPU_HSRR1     	(*(short int *) (TPU_BASE+0x1a))
#define TPU_CPR0      	(*(short int *) (TPU_BASE+0x1c))
#define TPU_CPR1      	(*(short int *) (TPU_BASE+0x1e))
#define TPU_CISR      	(*(short int *) (TPU_BASE+0x20))
#define TPU_LR      	(*(short int *) (TPU_BASE+0x22))
#define TPU_SGLR      	(*(short int *) (TPU_BASE+0x24))
#define TPU_DCNR      	(*(short int *) (TPU_BASE+0x26))

#define TPU_RAM   	(TPU_BASE+0x100)
